# Generated by Django 3.0.5 on 2020-04-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_title', models.CharField(max_length=200)),
                ('ing_quantity', models.CharField(max_length=200)),
                ('ing_price', models.IntegerField()),
                ('ing_expir', models.BooleanField()),
            ],
        ),
    ]
