# Generated by Django 3.0.5 on 2020-04-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ing_expir',
            new_name='Ingredient_expir',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ing_price',
            new_name='Ingredient_price',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ing_quantity',
            new_name='Ingredient_quantity',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ing_title',
            new_name='Ingredient_title',
        ),
    ]
